version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      - log_server

  log_server:
    build:
      context: ./
      dockerfile: Dockerfile-log-server

    expose:
      - "5237/udp"
